
static char *lang_names[] = {
    "Brazilian    by Ivan F. Martinez <ivanfm@os2brasil.com.br>",
    "Bulgarian    by Martin Mavrov <martin.mavrov@bulgaria.com>",
    "Chinese      by Lord Lee",
    "Czech        by Milan Ulej <milan.ulej@npsumava.cz>",
    "Danish       by Kim Poulsen <kpo@daimi.aau.dk>",
    "Dutch        by HH|CE <info@HHCE.nl>",
    "English      by Sergey Ayukov <asv@sai.msu.ru>",
    "Finnish      by Teemu Mannermaa <wicked@clinet.fi>",
    "French       by Didier Toulouze <dito@club-internet.fr>",
    "German       by Hubert Brentano <hubert.brentano@koeln.netsurf.de>",
    "Hungarian    by Toth Ferenc <etus@alarmix.net>",
    "Italian      by Pantaleo Nacci <drdivago@mclink.it>",
    "Japanese     by Kazuyoshi Shimizu <kshimz@dd.iij4u.or.jp>",
    "Korean       by Jun Ha Lee <smileguy@jayu.sarang.net>",
    "Norwegian    by Kristoffer Viddal <viddal@writeme.com>",
    "Polish       by Piotr Klaban <makler@man.torun.pl>",
    "Russian      by Sergey Ayukov <asv@sai.msu.ru>",
    "Slovak       by Thomas Ulej <ulej@stonline.sk>",
    "Spanish      by Jose Ruiz <jruiz@ctv.es>",
    "Swedish      by Lennart Carlson <beetle@swipnet.se>",
    "Ukrainian    by Igor Krassikov <kiv@post.materials.kiev.ua>"};

static char *langs[] = {
    "brazilian",
    "bulgarian",
    "chinese",
    "czech",
    "danish",
    "dutch",
    "english",
    "finnish",
    "french",
    "german",
    "hungarian",
    "italian",
    "japanese",
    "korean",
    "norwegian",
    "polish",
    "russian",
    "slovak",
    "spanish",
    "swedish",
    "ukrainian"};
